name: reminder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.5.0
  google_fonts: ^7.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.6.1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true